# -*- coding: utf-8 -*-
"""colab-github-clone-use.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jXu3xm1qICJkfaWj3_jSxelM-gDqjFL4
"""

!git clone https://github.com/philipperemy/keras-attention-mechanism.git

ls -alrt

cd keras-attention-mechanism

import numpy as np

from attention_utils import get_activations, get_data

np.random.seed(1337)  # for reproducibility
from keras.models import *
from keras.layers import Input, Dense, merge