# -*- coding: utf-8 -*-
"""python-class-test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18dZvMnf821wKahOB9B_oXMPlnVD_uUx-
"""

class python_class():
  def __init__(self) :
      print('__init__')

  def __build__(self) :
      print('__build__')

  def __call__(self) :
      print('__call__')

  def __step__(self) :
      print('__step__')

py_class = python_class()