# -*- coding: utf-8 -*-
"""Keras-Attention-Visualize-Fork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zj1ch2DvBqCB2cRXkzCXAxnu_xLLP06E
"""

#https://github.com/likejazz/jupyter-notebooks/tree/master/deep-learning/keras-attention
#>> https://github.com/datalogue/keras-attention.git

!git clone https://github.com/jukyellow/keras-attention.git

ls -alrt

cd keras-attention

#!pip install -r requirements-gpu.txt

!pip install -r requirements.txt

ls -alrt

cd data

!python generate.py

ls -alrt

cd ..

#epochs default 50! but long time, I set 5 times
!python run.py

!python visualize.py -e examples.txt

ls -alrt

cd attention_maps

ls -alrt

from google.colab import files
files.download('January 5 2016.pdf')

files.download('June 8th 1999.pdf')